# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bias_detector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1327, 1069)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome = QtWidgets.QLabel(self.centralwidget)
        self.Welcome.setGeometry(QtCore.QRect(420, 0, 621, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome.setFont(font)
        self.Welcome.setObjectName("Welcome")
        self.dataset = QtWidgets.QLabel(self.centralwidget)
        self.dataset.setGeometry(QtCore.QRect(270, 110, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.dataset.setFont(font)
        self.dataset.setObjectName("dataset")
        self.Select = QtWidgets.QPushButton(self.centralwidget)
        self.Select.setGeometry(QtCore.QRect(1010, 110, 75, 16))
        self.Select.setObjectName("Select")
        self.target = QtWidgets.QLabel(self.centralwidget)
        self.target.setGeometry(QtCore.QRect(270, 140, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.target.setFont(font)
        self.target.setObjectName("target")
        self.depth = QtWidgets.QLabel(self.centralwidget)
        self.depth.setGeometry(QtCore.QRect(270, 220, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.depth.setFont(font)
        self.depth.setObjectName("depth")
        self.leaf = QtWidgets.QLabel(self.centralwidget)
        self.leaf.setGeometry(QtCore.QRect(670, 220, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.leaf.setFont(font)
        self.leaf.setObjectName("leaf")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(270, 330, 151, 23))
        self.Start.setObjectName("Start")
        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(250, 370, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.results.setFont(font)
        self.results.setObjectName("results")
        self.textBrowser_dataset = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_dataset.setGeometry(QtCore.QRect(480, 100, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.textBrowser_dataset.setFont(font)
        self.textBrowser_dataset.setObjectName("textBrowser_dataset")
        self.textBrowser_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_results.setGeometry(QtCore.QRect(250, 490, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.textBrowser_results.setFont(font)
        self.textBrowser_results.setObjectName("textBrowser_results")
        self.lineEdit_target = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target.setGeometry(QtCore.QRect(540, 140, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.lineEdit_target.setFont(font)
        self.lineEdit_target.setObjectName("lineEdit_target")
        self.spinBox_depth = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_depth.setGeometry(QtCore.QRect(540, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.spinBox_depth.setFont(font)
        self.spinBox_depth.setObjectName("spinBox_depth")
        self.spinBox_leaf = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_leaf.setGeometry(QtCore.QRect(930, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.spinBox_leaf.setFont(font)
        self.spinBox_leaf.setObjectName("spinBox_leaf")
        self.dtr = QtWidgets.QPushButton(self.centralwidget)
        self.dtr.setGeometry(QtCore.QRect(270, 930, 291, 23))
        self.dtr.setObjectName("dtr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 60, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 240, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.depth_2 = QtWidgets.QLabel(self.centralwidget)
        self.depth_2.setGeometry(QtCore.QRect(270, 280, 721, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.depth_2.setFont(font)
        self.depth_2.setObjectName("depth_2")
        self.spinBox_min_number = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_min_number.setGeometry(QtCore.QRect(1060, 290, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.spinBox_min_number.setFont(font)
        self.spinBox_min_number.setMaximum(100000)
        self.spinBox_min_number.setProperty("value", 2)
        self.spinBox_min_number.setObjectName("spinBox_min_number")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(270, 960, 101, 23))
        self.Reset.setObjectName("Reset")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 470, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(180, 560, 941, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 530, 801, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.export_latex = QtWidgets.QPushButton(self.centralwidget)
        self.export_latex.setGeometry(QtCore.QRect(870, 960, 111, 23))
        self.export_latex.setObjectName("export_latex")
        self.export_excel = QtWidgets.QPushButton(self.centralwidget)
        self.export_excel.setGeometry(QtCore.QRect(870, 930, 111, 23))
        self.export_excel.setObjectName("export_excel")
        self.depth_3 = QtWidgets.QLabel(self.centralwidget)
        self.depth_3.setGeometry(QtCore.QRect(270, 300, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.depth_3.setFont(font)
        self.depth_3.setObjectName("depth_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(1000, 310, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setDecimals(5)
        self.doubleSpinBox.setMaximum(100000000.99)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.lineEdit_predicted = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_predicted.setGeometry(QtCore.QRect(560, 180, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.lineEdit_predicted.setFont(font)
        self.lineEdit_predicted.setObjectName("lineEdit_predicted")
        self.target_2 = QtWidgets.QLabel(self.centralwidget)
        self.target_2.setGeometry(QtCore.QRect(270, 180, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.target_2.setFont(font)
        self.target_2.setObjectName("target_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 400, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textBrowser_sample_size = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_sample_size.setGeometry(QtCore.QRect(250, 430, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.textBrowser_sample_size.setFont(font)
        self.textBrowser_sample_size.setObjectName("textBrowser_sample_size")
        self.target_question = QtWidgets.QPushButton(self.centralwidget)
        self.target_question.setGeometry(QtCore.QRect(1050, 146, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.target_question.setFont(font)
        self.target_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.target_question.setObjectName("target_question")
        self.dataset_question = QtWidgets.QPushButton(self.centralwidget)
        self.dataset_question.setGeometry(QtCore.QRect(1100, 108, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.dataset_question.setFont(font)
        self.dataset_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.dataset_question.setObjectName("dataset_question")
        self.depth_question = QtWidgets.QPushButton(self.centralwidget)
        self.depth_question.setGeometry(QtCore.QRect(630, 220, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.depth_question.setFont(font)
        self.depth_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.depth_question.setObjectName("depth_question")
        self.leaf_question = QtWidgets.QPushButton(self.centralwidget)
        self.leaf_question.setGeometry(QtCore.QRect(1020, 220, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.leaf_question.setFont(font)
        self.leaf_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.leaf_question.setObjectName("leaf_question")
        self.mim_sample_question = QtWidgets.QPushButton(self.centralwidget)
        self.mim_sample_question.setGeometry(QtCore.QRect(1150, 288, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.mim_sample_question.setFont(font)
        self.mim_sample_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.mim_sample_question.setObjectName("mim_sample_question")
        self.min_bias_question = QtWidgets.QPushButton(self.centralwidget)
        self.min_bias_question.setGeometry(QtCore.QRect(1090, 309, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.min_bias_question.setFont(font)
        self.min_bias_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.min_bias_question.setObjectName("min_bias_question")
        self.whole_sample_question = QtWidgets.QPushButton(self.centralwidget)
        self.whole_sample_question.setGeometry(QtCore.QRect(1070, 435, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.whole_sample_question.setFont(font)
        self.whole_sample_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.whole_sample_question.setObjectName("whole_sample_question")
        self.overall_mean_question = QtWidgets.QPushButton(self.centralwidget)
        self.overall_mean_question.setGeometry(QtCore.QRect(1070, 495, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.overall_mean_question.setFont(font)
        self.overall_mean_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.overall_mean_question.setObjectName("overall_mean_question")
        self.graph_question = QtWidgets.QPushButton(self.centralwidget)
        self.graph_question.setGeometry(QtCore.QRect(570, 930, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.graph_question.setFont(font)
        self.graph_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.graph_question.setObjectName("graph_question")
        self.csv_question = QtWidgets.QPushButton(self.centralwidget)
        self.csv_question.setGeometry(QtCore.QRect(990, 930, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.csv_question.setFont(font)
        self.csv_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.csv_question.setObjectName("csv_question")
        self.reset_question = QtWidgets.QPushButton(self.centralwidget)
        self.reset_question.setGeometry(QtCore.QRect(380, 960, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.reset_question.setFont(font)
        self.reset_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.reset_question.setObjectName("reset_question")
        self.latex_question = QtWidgets.QPushButton(self.centralwidget)
        self.latex_question.setGeometry(QtCore.QRect(990, 960, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.latex_question.setFont(font)
        self.latex_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.latex_question.setObjectName("latex_question")
        self.start_question = QtWidgets.QPushButton(self.centralwidget)
        self.start_question.setGeometry(QtCore.QRect(430, 330, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.start_question.setFont(font)
        self.start_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.start_question.setObjectName("start_question")
        self.prediction_question = QtWidgets.QPushButton(self.centralwidget)
        self.prediction_question.setGeometry(QtCore.QRect(1070, 187, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.prediction_question.setFont(font)
        self.prediction_question.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border: 2px solid #555;\n"
"    border-radius: 10px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.prediction_question.setObjectName("prediction_question")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1327, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bias detector"))
        self.Welcome.setText(_translate("MainWindow", "Welcome to the bias detector!"))
        self.dataset.setText(_translate("MainWindow", "Please choose the dataset:"))
        self.Select.setText(_translate("MainWindow", "Select"))
        self.target.setText(_translate("MainWindow", "Please enter the target variable:"))
        self.depth.setText(_translate("MainWindow", "Please enter the depth of the tree:"))
        self.leaf.setText(_translate("MainWindow", "Please enter the leaf of the tree:"))
        self.Start.setText(_translate("MainWindow", "Start to detect bias"))
        self.results.setText(_translate("MainWindow", "The results:"))
        self.dtr.setText(_translate("MainWindow", "Show the graph of the decision tree meta model"))
        self.label.setText(_translate("MainWindow", "Required input:"))
        self.label_2.setText(_translate("MainWindow", "Optional input:"))
        self.depth_2.setText(_translate("MainWindow", "Please enter the minimum number of samples required to split an internal node (default = 2):"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.label_3.setText(_translate("MainWindow", "The overall mean:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "sub-group"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "mean error"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "sample size"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "confidence interval"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "bias score"))
        self.label_4.setText(_translate("MainWindow", "The bias in each sub-group (sorted in descending order according to the value of bias score):"))
        self.export_latex.setText(_translate("MainWindow", "Export To Latex"))
        self.export_excel.setText(_translate("MainWindow", "Export To CSV"))
        self.depth_3.setText(_translate("MainWindow", "Please enter the minimum bias score magnitude you are interested in (default = 0):"))
        self.target_2.setText(_translate("MainWindow", "Please enter the prediction variable:"))
        self.label_5.setText(_translate("MainWindow", "The whole sample size:"))
        self.target_question.setText(_translate("MainWindow", "?"))
        self.dataset_question.setText(_translate("MainWindow", "?"))
        self.depth_question.setText(_translate("MainWindow", "?"))
        self.leaf_question.setText(_translate("MainWindow", "?"))
        self.mim_sample_question.setText(_translate("MainWindow", "?"))
        self.min_bias_question.setText(_translate("MainWindow", "?"))
        self.whole_sample_question.setText(_translate("MainWindow", "?"))
        self.overall_mean_question.setText(_translate("MainWindow", "?"))
        self.graph_question.setText(_translate("MainWindow", "?"))
        self.csv_question.setText(_translate("MainWindow", "?"))
        self.reset_question.setText(_translate("MainWindow", "?"))
        self.latex_question.setText(_translate("MainWindow", "?"))
        self.start_question.setText(_translate("MainWindow", "?"))
        self.prediction_question.setText(_translate("MainWindow", "?"))
