# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#s
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, Ui_SecondWindow):
        Ui_SecondWindow.setObjectName("Ui_SecondWindow")
        Ui_SecondWindow.resize(1036, 646)
        self.centralwidget = QtWidgets.QWidget(Ui_SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 0, 1031, 621))
        self.image.setObjectName("image")
        Ui_SecondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_SecondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 23))
        self.menubar.setObjectName("menubar")
        Ui_SecondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_SecondWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_SecondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_SecondWindow)

    def retranslateUi(self, Ui_SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_SecondWindow.setWindowTitle(_translate("Ui_SecondWindow", "MainWindow"))
        self.image.setText(_translate("Ui_SecondWindow", "TextLabel"))
